name: biowzrd
channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - biopython
  - biom-format
  - blast
  - bowtie2
  - fastp
  - fastqc
  - multiqc
  - samtools
  - seqkit
  - h5py
  - dendropy
  - entrez-direct
  - trimmomatic
  - raxml
  - krona
  - muscle
  - sra-tools
  - enaBrowserTools
  - git-lfs
  - pigz
  - psutil
  - tenacity
  - parallel
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-reshape2
  - r-stringr
  - r-data.table
  - r-tibble
  - r-readr
  - pip
  - pip:
      - reportlab
      - urllib3
